"""Parameter spec registry — Python mirror of the frontend's paramSpecs.json.

The JSON file next to this module is GENERATED by `pnpm --filter frontend
gen:params`; do not edit it by hand. The frontend remains the authoritative
validator — this mirror lets the agent reject (and report) invalid values
before they ever reach the client.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_SPECS_PATH = Path(__file__).resolve().parent / "param_specs.json"

_FORBIDDEN_SEGMENTS = frozenset({"__proto__", "constructor", "prototype"})


def _load() -> list[dict[str, Any]]:
    with _SPECS_PATH.open(encoding="utf-8") as f:
        return json.load(f)["params"]


PARAM_SPECS: list[dict[str, Any]] = _load()


def match_spec(path: str) -> dict[str, Any] | None:
    """Find the spec for a concrete path, honoring '*' single-segment wildcards."""
    parts = path.split(".")
    for spec in PARAM_SPECS:
        spec_parts = spec["path"].split(".")
        if len(spec_parts) != len(parts):
            continue
        if all(sp == "*" or sp == p for sp, p in zip(spec_parts, parts)):
            return spec
    return None


def validate_param(path: str, value: Any) -> tuple[Any | None, str | None]:
    """Validate (and lightly coerce) a value against the spec for `path`.

    Returns (coerced_value, None) on success or (None, error_message).
    Integers are rounded; numeric strings are coerced. Out-of-range values
    are rejected (not clamped) so the LLM gets explicit feedback.
    """
    parts = path.split(".")
    if any(p in _FORBIDDEN_SEGMENTS for p in parts):
        return None, f"forbidden path segment in '{path}'"

    spec = match_spec(path)
    if spec is None:
        return None, f"unknown parameter path '{path}'"

    label = spec.get("label", path)
    ptype = spec["type"]

    if ptype == "boolean":
        if not isinstance(value, bool):
            return None, f"{label} expects boolean, got {value!r}"
        return value, None

    if ptype == "enum":
        values = spec["values"]
        if not isinstance(value, str) or value not in values:
            return None, f"{label} expects one of {values}, got {value!r}"
        return value, None

    # number / integer
    if isinstance(value, bool):  # bool is an int subclass — reject explicitly
        return None, f"{label} expects a number, got {value!r}"
    if isinstance(value, str):
        try:
            value = float(value.strip())
        except (ValueError, TypeError):
            return None, f"{label} expects a number, got {value!r}"
    if not isinstance(value, (int, float)):
        return None, f"{label} expects a number, got {value!r}"

    v = float(value)
    if ptype == "integer":
        v = round(v)
    if v < spec["min"] or v > spec["max"]:
        return None, f"{label} must be between {spec['min']} and {spec['max']}, got {v}"
    return int(v) if ptype == "integer" else v, None


def validate_mutations(mutations: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[str]]:
    """Validate a list of {path, value} mutations.

    Returns (valid_mutations, error_messages). Special non-parameter paths
    (modulation.*, effectChain) are produced by dedicated tools with their
    own validation and pass through untouched.
    """
    valid: list[dict[str, Any]] = []
    errors: list[str] = []
    for mut in mutations:
        path = mut.get("path", "")
        if path.startswith("modulation.") or path == "effectChain":
            valid.append(mut)
            continue
        coerced, err = validate_param(path, mut.get("value"))
        if err:
            errors.append(err)
        else:
            # Preserve passthrough metadata (e.g. 'track' for multi-track routing)
            valid.append({**mut, "path": path, "value": coerced})
    return valid, errors
